version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    network_mode: "host"
    volumes:
      - /tmp/sslcert:/tmp/sslcert
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    network_mode: "host"
    volumes:
      - /tmp/sslcert:/tmp/sslcert